# Lesson 3 - Homework - Pandas and Numpy

### Hi again! :)

#### For today's homework, you will further explore the dataset recipe.csv. So start with importing the two key libraries: NumPy and pandas and loading the .csv file. Use the first column as index.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("data\\recipes.csv",index_col=0)
df

vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0          True        True       True        False          1.0   
1          True        True      False        False          0.0   
2         False       False      False        False          3.0   
3          True       False       True        False          2.0   
4         False        True      False        False         31.0   
..          ...         ...        ...          ...          ...   
145       False        True       True        False         18.0   
146        True       False      False        False          1.0   
147        True        True       True         True         93.0   
148        True        True      False        False          5.0   
149        True        True       True         True        100.0   

     aggregateLikes      id  \
0                 3  633998   
1                 1  634426   
2                 1  635085   
3                 1  663229   
4                 3  651437   
..              ...     ...   
145              13  638315   
146               2  656248   
147               2  637297   
148               1  659412   
149               4  647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  ...  VitaminB3Amount VitaminB3percentOfDailyNeed  \
0                45  ...             0.49                        2.44   
1                45  ...              NaN                         NaN   
2                45  ...             2.63                       13.13   
3                45  ...             0.65                        3.26   
4                45  ...             0.66                        3.29   
..              ...  ...              ...                         ...   
145              45  ...             0.53                        2.67   
146              45  ...             0.21                        1.07   
147              45  ...             4.77                       23.83   
148              45  ...             1.15                        5.73   
149              30  ...             0.21                        1.05   

     VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
0               0.03                         2.26          18.11   
1                NaN                          NaN            NaN   
2               0.32                        21.09         100.80   
3               0.10                         6.47          26.79   
4               0.07                         4.64         162.84   
..               ...                          ...            ...   
145             0.15                        10.23         102.67   
146             0.03                         1.68          19.82   
147             0.45                        29.70         141.16   
148             0.12                         7.85          55.64   
149              NaN                          NaN          27.96   

     CalciumpercentOfDailyNeed  AlcoholAmount  AlcoholpercentOfDailyNeed  \
0                         1.81            NaN                        NaN   
1                          NaN            NaN                       

#### Drop all the columns that are of Boolean type. We won't need them.

#### Keep the new dataframe stored in the same variable as the first one.

In [3]:
df.dtypes
df.head()
drop_columns=['vegetarian','glutenFree','dairyFree','veryHealthy']
df = df.drop(drop_columns, axis=1)

#### In some of the columns, there are less than 100 values available. Please drop them, too. We will learn how to deal with non-available values next time.

#### Keep the new dataframe stored in the same variable as the first one.

healthScore  aggregateLikes      id  \
0            1.0               3  633998   
1            0.0               1  634426   
2            3.0               1  635085   
3            2.0               1  663229   
4           31.0               3  651437   
..           ...             ...     ...   
145         18.0              13  638315   
146          1.0               2  656248   
147         93.0               2  637297   
148          5.0               1  659412   
149        100.0               4  647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  servings  \
0                45         8   
1                45        10   
2                45         5   
3                45        12   
4                45         8   
..              ...       ...   
145              45         6   
146              45        16   
147              45         4   
148              45         4   
149              30         4   

                                             sourceUrl  CaloriesAmount  \
0    https://www.foodista.com/recipe/K65SYB3F/banan...          175.67   
1    https://www.foodista.com/recipe/ZCDX55YK/basil...           85.52   
2    https://www.foodista.com/recipe/HPYY5YMF/black...          700.30   
3    http://www.foodista.com/recipe/5K2BY4P7/the-be...          169.88   
4    https://www.foodista.com/recipe/SWFHGWPH/medit...          144.42   
..                                                 ...             ...   
145  https://www.foodista.com/recipe/R66F23JJ/chick...          312.19   
146  https://www.foodista.com/recipe/L5G2TX8B/pinot...          213.58   
147  https://www.foodista.com/recipe/BQBJ3XVS/cauli...          455.50   
148  https://www.foodista.com/recipe/Q33QTX2N/saute...           73.47   
149  http://www.foodista.com/recipe/2LQW8RTQ/indian...          132.00   

     CaloriespercentOfDailyNeed  ...  VitaminB3Amount  \
0                          8.78  ...             0.49   
1                          4.28  ...              NaN   
2                         35.01  ...             2.63   
3                          8.49  ...             0.65   
4                          7.22  ...             0.66   
..                          ...  ...              ...   
145                       15.61  ...             0.53   
146                       10.68  ...             0.21   
147                       22.78  ...             4.77   
148                        3.67  ...             1.15   
149                        6.60  ...             0.21   

     VitaminB3percentOfDailyNeed  VitaminB1Amount  \
0                           2.44             0.03   
1                            NaN              NaN   
2                          13.13             0.32   
3                           3.26             0.10   
4                           3.29             0.07   
..                           ...              ...   
145                         2.67             0.15   
146                         1.07             0.03   
147                        23.83             0.45   
148                         5.73             0.12   
149                  

#### Enough dropping. How big is your DataFrame now?

In [4]:
df.shape

(150, 74)

#### Too big. The columns are fine, but we will restrict ourselves to 50 recipes. Please choose any 50 recipes (hint: maybe the first 50? :) ).

#### Keep the new dataframe stored in the same variable as the first one.

In [5]:
df = df.head(50)
df

healthScore  aggregateLikes       id  \
0           1.0               3   633998   
1           0.0               1   634426   
2           3.0               1   635085   
3           2.0               1   663229   
4          31.0               3   651437   
5          30.0               1  1096267   
6           5.0               1   647894   
7           0.0               1   982367   
8           4.0               1   641943   
9          62.0               1  1095768   
10         36.0              37   639606   
11          1.0               1   643877   
12          4.0               4   639209   
13          2.0               1   653353   
14         16.0               2   661036   
15          8.0               1   653399   
16         12.0               1   635793   
17         13.0               1   649882   
18          4.0               2   664533   
19          5.0               2   658126   
20         20.0               1   642892   
21         21.0              18   632874   
22         16.0               1   636600   
23          9.0               1   635447   
24          6.0               7   645416   
25          0.0               1   654516   
26         42.0               1   649225   
27         19.0               2   641962   
28          3.0               7   655145   
29         19.0               1   648742   
30         17.0               1  1096306   
31          5.0             249   716421   
32          6.0               1   652758   
33         54.0               2   641443   
34         78.0              15   661340   
35          9.0               6   634605   
36         57.0               1   647124   
37         17.0               1   658495   
38          9.0               1   649300   
39          7.0               6  1098357   
40         12.0               7   641904   
41          1.0               1   657875   
42          2.0               8   655098   
43         44.0               1   622825   
44          0.0               1  1095774   
45          2.0               0   715473   
46         49.0               1  1096242   
47          2.0              13   640827   
48         43.0               1   650126   
49          9.0               2   654953   

                                                title  pricePerServing  \
0                           Banana Blueberry Pancakes            55.79   
1             Basil and Orange Confit Compound Butter            15.07   
2                            Black Bottom Banana Bars            78.85   
3                 The Best Raw Chocolate Chip Cookies            54.64   
4                 Mediterranean Spinach Artichoke Dip           115.26   
5                            Turkey Burgers with Slaw           387.61   
6                      Individual Strawberry Souffles           101.40   
7                              Fidget Spinner Cookies            21.60   
8                             Easy Crawfish Jambalaya           126.04   
9   Bulgur Wheat Salad with Chickpeas, Bell Pepper...           229.28   
10                             Classic Greek Moussaka           441.50   
11                           Fromage Blanc Cheesecake           203.73   
12                               Chocolate Spelt Cake            74.24   
13          Nutella Cupcakes & Peanut Butter Frosting            59.65   
14                         Spicy Carrot Amaranth Soup           220.53   
15                                         Nutty Rice            99.58   
16                                 Braised Anise Beef           157.95   
17                Lemony Brown Rice With Baby Spinach           168.13   
18                           Vegetable Cheddar Quiche            71.80   
19                             Red Wine Stewed Oxtail           416.91   
20                        Fire Roasted Tomato Chutney            74.69   
21  Asian Salmon Burgers With Tangy Ginger Lime Sauce           370.04   
22                              Butternut Squash Soup    

#### Display only the columns referring to Fiber.

In [6]:
df.loc[:,['FiberAmount', 'FiberpercentOfDailyNeed']]

FiberAmount  FiberpercentOfDailyNeed
0          3.81                    15.22
1           NaN                      NaN
2          4.60                    18.40
3          3.45                    13.81
4          2.41                     9.64
5          2.95                    11.81
6          1.98                     7.94
7          1.56                     6.24
8          1.57                     6.27
9         27.10                   108.42
10        11.57                    46.28
11         1.54                     6.17
12         5.27                    21.07
13         2.57                    10.27
14         6.63                    26.53
15         4.52                    18.08
16          NaN                      NaN
17         3.19                    12.78
18         1.43                     5.71
19         1.78                     7.14
20         2.68                    10.71
21         1.09                     4.35
22         3.51                    14.03
23         0.68                     2.71
24         4.87                    19.49
25         1.72                     6.86
26         5.95                    23.82
27         6.96                    27.83
28         2.20                     8.79
29         3.12                    12.48
30        14.69                    58.75
31         4.34                    17.36
32         1.31                     5.23
33        11.79                    47.16
34         6.38                    25.51
35         1.14                     4.57
36         5.60                    22.39
37         5.79                    23.17
38         4.70                    18.81
39         1.71                     6.83
40         4.56                    18.23
41         0.81                     3.23
42         1.13                     4.50
43        12.40                    49.62
44         0.59                     2.36
45         0.91                     3.66
46         7.48                    29.91
47         1.37                     5.48
48         6.90                    27.59
49         1.92                     7.67

#### And now the columns referring to Fiber for recipes from rows numbered 10 to 30.

In [7]:
df.loc[10:30,['FiberAmount', 'FiberpercentOfDailyNeed']]

FiberAmount  FiberpercentOfDailyNeed
10        11.57                    46.28
11         1.54                     6.17
12         5.27                    21.07
13         2.57                    10.27
14         6.63                    26.53
15         4.52                    18.08
16          NaN                      NaN
17         3.19                    12.78
18         1.43                     5.71
19         1.78                     7.14
20         2.68                    10.71
21         1.09                     4.35
22         3.51                    14.03
23         0.68                     2.71
24         4.87                    19.49
25         1.72                     6.86
26         5.95                    23.82
27         6.96                    27.83
28         2.20                     8.79
29         3.12                    12.48
30        14.69                    58.75

#### Cool. Now choose your favourite recipe and display only the respective row in the DataFrame.

In [8]:
df.loc[df['title'] == 'Banana Blueberry Pancakes',:]

healthScore  aggregateLikes      id                      title  \
0          1.0               3  633998  Banana Blueberry Pancakes   

   pricePerServing  readyInMinutes  servings  \
0            55.79              45         8   

                                           sourceUrl  CaloriesAmount  \
0  https://www.foodista.com/recipe/K65SYB3F/banan...          175.67   

   CaloriespercentOfDailyNeed  ...  VitaminB3Amount  \
0                        8.78  ...             0.49   

   VitaminB3percentOfDailyNeed  VitaminB1Amount  VitaminB1percentOfDailyNeed  \
0                         2.44             0.03                         2.26   

   CalciumAmount  CalciumpercentOfDailyNeed  AlcoholAmount  \
0          18.11                       1.81            NaN   

   AlcoholpercentOfDailyNeed  CaffeineAmount  CaffeinepercentOfDailyNeed  
0                        NaN             NaN                         NaN  

[1 rows x 74 columns]

#### And now the columns referring to Fiber FOR your favourite recipe.

In [9]:
df.loc[df['title'] == 'Banana Blueberry Pancakes',['FiberAmount', 'FiberpercentOfDailyNeed']]

FiberAmount  FiberpercentOfDailyNeed
0         3.81                    15.22

#### One last thing. What is the difference between accessing the column "vegetarian" in those two ways:
- df["vegetarian"]
- df[["vegetarian"]]

#### (df is the name of your DataFrame).

Hint: what are the types of these two?

## Please remember that difference.

# Exercises on Numpy

1. Write a NumPy program to create an array of the integers from 10 to 50

In [30]:
arr=np.arange(10,51,1)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

2. And print the Even and odd integers from the above array

In [40]:
#arrnew=np.arange(arr[0],arr[40],2)
#print(arrnew)
#not able to get 50
#arrnew2=np.arange(arr[1],arr[40],2)
#print(arrnew2)

arr_even=[]
arr_odd=[]
for i in arr:
    if ((i%2)==0):
        arr_even=np.append(arr_even,i)
    else:
        arr_odd=np.append(arr_odd,i)
print(arr_even.astype(np.int))
print(arr_odd.astype(np.int))
#after the calculation (i%2)==0, the array is converted to float

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


3. Write a NumPy program to convert an array to a float type. 

__Expected output__:

Original array
[1, 2, 3, 4]

Array converted to a float type:
[ 1. 2. 3. 4.]

In [41]:
newarr=arr.astype(np.float)
newarr

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50.])

4. Create a 2X2 integer array and print it's values and then print max along the axis 1 of that result.


In [42]:
arr = np.array([[1, 2], [4, 5]])
print(arr)
np.amax(arr, axis=1)

[[1 2]
 [4 5]]


array([2, 5])

5. Create a 2-d array named ints and perform the following operations

- Print second row of ints

- Print all elements of ints that are greater than six

- Double every element of ints

- Replace the third column of ints

In [49]:
ints = np.array([[1,2,3,4],[5,6,7,8]])
print(ints)
#printing 2nd row
print(ints[1,:])
#printing all elements greater than 6
print(ints[ints>6])
#doubling every element of ints
print(ints*2)
#replacing elements in third column
ints[:,2]=[5,9]
print(ints)

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8]
[7 8]
[[ 2  4  6  8]
 [10 12 14 16]]
[[1 2 5 4]
 [5 6 9 8]]


## #See you!!1