 ## CLASS-EXERCISE 

1. Create a 2-d and 3-d numpy integer array 

In [2]:
import numpy as np
two_dim = np.array([[1, 2], [4, 5]])
three_dim = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

2. Create a 2X2 integer array and show it's dimensions

In [4]:
print(two_dim.ndim)
print(three_dim.ndim)

2
3


3. Create a numpy array and  print the sum of third and fourth elements from the array 

In [6]:
arr = np.array([1,2,3,4,5,6])
arr[2]+arr[3]

7

4. Slice the below array to get the the second item to the excluding fifth item

arr = np.array([10, 15, 20, 25, 30, 35, 40])

In [23]:
arr = np.array([10,15,20,25,30,35,40])
arr[1:4]

array([15, 20, 25])

5. Try example 4. using STEP method

In [14]:
arr[1:4:1]

array([15, 20, 25])

6. Create a integer array and change data type from integer to boolean



In [19]:
arr.dtype
newarr = arr.astype('bool')
newarr.dtype
newarr

array([ True,  True,  True,  True,  True,  True,  True])

7. Use NumPy syntax to check the shape of an array.

arr = np.array([1, 2, 3, 4, 5])

In [30]:
print(arr)
print(arr.shape)
arr2 = np.array([[10,15,20,25,30,35,40]])
print(arr2.shape)

[10 15 20 25 30 35 40]
(7,)
(1, 7)


8. Find the indexes where the values are even:

arr = [16, 8, 3, 7, 15, 24]

In [33]:
arr = [16,8,3,7,15,24]
for x in arr:
    if((x%2)==0):
        print np.where(arr == x)

SyntaxError: invalid syntax (<ipython-input-33-6477381d9087>, line 4)

9. Create a numpy array of 5 person names and sort the values alpbabetically

10. Use the correct NumPy method to return a sorted array.

  arr = np.array([3, 2, 0, 1])